name: CodeQL

on:
  push:
    branches: [main, beta, alpha]
  pull_request:
    branches: [main, beta, alpha]

permissions: read-all

jobs:
  codeql:
    name: Code QL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository for code analysis
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Initialize CodeQL
        uses: github/codeql-action/init@678fc3afe258fb2e0cdc165ccf77b85719de7b3c
        with:
          languages: javascript
          queries: security-extended

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@678fc3afe258fb2e0cdc165ccf77b85719de7b3c
